---
- name: Playbook to configure a windows azure vm via invoke runcommand 
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - defaults/main.yml
  vars:
    # azure vms to configure
    vmlist: 
    - name: ttfappwevm01
      resource_group: rg-module-test-01
      os_family: windows

    - name: ttfappwevm01
      resource_group: rg-module-test-01
      os_family: windows
    
  tasks:
  - name: Configure the azure vm {{ vm_name }}/{{ vm_resource_group }}
    debug:
      msg: | 
        Client {{ client_id }} is configuring VM: {{ item.name }}/{{ item.resource_group }} in Azure subscription {{ subscription_id }}
    loop: "{{ vmlist }}"

  - name: invoke_azurerm_vm_run_command
    invoke_azurerm_vm_run_command:
      vm_name: "{{ item.name }}"
      vm_resource_group: "{{ item.resource_group }}"
      run_command: |
        write-host "line 1"
        write-host "line 2"
        get-wmiobject win32_computersystem
      client_id: "{{ client_id }}"
      tenant_id: "{{ tenant }}"
      client_secret: "{{ secret }}"
      subscription_id: "{{ subscription_id }}"
    loop: "{{ vmlist }}"
     
    register: vm_run_cmd_output
    #no_log: true
    ignore_errors: true

  - name: Display run_command output
    debug:
      msg: |
        command_result : {{ vm_run_cmd_output }}
    ignore_errors: true
